version: '2.1'
services:
  start:
    image: spotify-radio
    build: .
    environment:
      PORT: 3000
    command: 
      - npm
      - run
      - start
    volumes:
      - .:/spotify-radio
      - node_modules:/spotify-radio/node_modules
    ports:
      - 3000:3000

  dev:
    image: spotify-radio
    build: .
    environment:
      PORT: 3000
    command: 
      - npm
      - run
      - dev
    volumes:
      - .:/spotify-radio
      - node_modules:/spotify-radio/node_modules
    ports:
      - 3000:3000

  test:
    image: spotify-radio
    build: .
    command: 
      - npm
      - run
      - test
    volumes:
      - .:/spotify-radio
      - node_modules:/spotify-radio/node_modules

  test-watch:
    image: spotify-radio
    build: .
    command: 
      - npm
      - run
      - test:watch
    volumes:
      - .:/spotify-radio
      - node_modules:/spotify-radio/node_modules

  test-coverage:
    image: spotify-radio
    build: .
    command: 
      - npm
      - run
      - test:coverage
    volumes:
      - .:/spotify-radio
      - node_modules:/spotify-radio/node_modules

volumes:
  node_modules: {}